FROM node:16 AS test-stage
WORKDIR /usr/src/app

COPY . .
RUN npm install
RUN CI=true npm run test

FROM node:16 AS build-stage
WORKDIR /usr/src/app
COPY --from=test-stage /usr/src/app .
RUN npm run build

RUN npm install -g serve

CMD ["serve", "-s", "build", "-p", "3000"]


# FROM nginx:1.20-alpine

#COPY --from=build-stage /usr/src/app/build /usr/share/nginx/html